import {destinations} from '../src/destinations.js';
const colors=[['Graphite','#60584c'],['Clay','#ae765c'],['Sage','#869575'],['Water','#829fa4']];let ink=colors[0][1],active=null,points=[],pointerId=null;let tool={width:2.5,opacity:1};const svg=document.querySelector('#drawing'),strokes=document.querySelector('#strokes'),status=document.querySelector('#status');
for(const [name,color] of colors){const b=document.createElement('button');b.className='pencil';b.setAttribute('aria-label',name+' paint');b.title=name+' paint';b.setAttribute('aria-pressed',String(color===ink));b.innerHTML='<svg viewBox="0 0 48 44" aria-hidden="true"><path d="M11 10C19 3 37 6 40 18S35 37 23 38 5 29 8 20Z" fill="'+color+'"/><path d="M14 13q8-5 15-2" fill="none" stroke="#fff9" stroke-width="2" stroke-linecap="round"/></svg>';b.onclick=()=>{ink=color;for(const el of document.querySelectorAll('.pencil'))el.setAttribute('aria-pressed',String(el===b));status.textContent=name+' ink.'};document.querySelector('.pencils').append(b)}
const implementsList=[['Pen',2.5,1,'M14 33 23 8 32 33 23 29Z M23 12v17 M18 37h10'],['Soft brush',10,.45,'M21 7h5l-1 18h-4Z M21 25q-8 4-7 14q10 4 18-1q-1-9-7-13 M18 31l-1 8m6-9v10m4-9 2 8'],['Broad brush',22,.7,'M20 8h6v17h10v10q-12 8-24 0V25h8Z M17 30v7m6-7v9m7-9v7']];
for(const [name,width,opacity,shape] of implementsList){const b=document.createElement('button');b.className='implement';b.setAttribute('aria-label',name);b.title=name;b.setAttribute('aria-pressed',String(name==='Pen'));b.innerHTML=`<svg viewBox="0 0 46 46" aria-hidden="true"><path d="${shape}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;b.onclick=()=>{tool={width,opacity};for(const el of document.querySelectorAll('.implement'))el.setAttribute('aria-pressed',String(el===b));status.textContent=name+' selected.'};document.querySelector('.implements').append(b)}
function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const matrix=svg.getScreenCTM();return matrix?p.matrixTransform(matrix.inverse()):null}
function curve(){const first=points[0],fmt=p=>`${p.x.toFixed(1)} ${p.y.toFixed(1)}`;if(points.length===1)return `M${fmt(first)}l.1 .1`;let d=`M${fmt(first)}`;for(let i=1;i<points.length;i++){const previous=points[i-1],current=points[i],mid={x:(previous.x+current.x)/2,y:(previous.y+current.y)/2};d+=`Q${fmt(previous)} ${fmt(mid)}`}return d+`Q${fmt(points[points.length-1])} ${fmt(points[points.length-1])}`}
function add(e){const p=point(e);if(active||!p||p.x<0||p.y<0||p.x>900||p.y>580)return;points=[p];pointerId=e.pointerId;active=document.createElementNS('http://www.w3.org/2000/svg','path');for(const [name,value] of Object.entries({fill:'none','stroke-linecap':'round','stroke-linejoin':'round',stroke:ink,'stroke-width':tool.width,'stroke-opacity':tool.opacity}))active.setAttribute(name,value);active.setAttribute('d',curve());strokes.append(active);svg.setPointerCapture(e.pointerId)}
function move(e){if(!active||e.pointerId!==pointerId)return;const p=point(e);if(!p)return;p.x=Math.max(0,Math.min(900,p.x));p.y=Math.max(0,Math.min(580,p.y));const last=points[points.length-1];if(Math.hypot(p.x-last.x,p.y-last.y)<1)return;points.push(p);active.setAttribute('d',curve())}
svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;add(e)});svg.addEventListener('pointermove',move);function finish(e){if(e.pointerId!==pointerId)return;if(active){move(e);status.textContent='A little mark, kept on this page.'}active=null;points=[];pointerId=null}svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',finish);svg.addEventListener('lostpointercapture',finish);
let clearedPage=null;
document.querySelector('#reset').onclick=()=>{if(!strokes.childElementCount&&!document.querySelector('#words').value)return;clearedPage={marks:[...strokes.children].map(mark=>mark.cloneNode(true)),words:document.querySelector('#words').value};strokes.replaceChildren();document.querySelector('#words').value='';status.textContent='A fresh sheet. Undo brings your previous page back.'};
document.querySelector('#undo').onclick=()=>{if(strokes.lastElementChild){strokes.lastElementChild.remove();status.textContent='Last mark undone.'}else if(clearedPage){strokes.append(...clearedPage.marks);document.querySelector('#words').value=clearedPage.words;clearedPage=null;status.textContent='Your previous page, brought back.'}};
document.querySelector('#note-toggle').onclick=()=>{const section=document.querySelector('.words');section.hidden=!section.hidden;document.querySelector('#note-toggle').setAttribute('aria-expanded',String(!section.hidden));if(!section.hidden)document.querySelector('#words').focus()};
document.querySelector('#download').onclick=()=>{const note=document.querySelector('#words').value;const lines=note.split('\n').flatMap(line=>line.match(/.{1,75}(?:\s|$)|.{1,75}/g)||['']);const pageHeight=Math.max(720,640+lines.length*24);const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','900');clone.setAttribute('height',String(pageHeight));clone.setAttribute('viewBox','0 0 900 '+pageHeight);const background=document.createElementNS('http://www.w3.org/2000/svg','rect');background.setAttribute('width','900');background.setAttribute('height',String(pageHeight));background.setAttribute('fill','#faf6e9');clone.prepend(background);const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x','30');text.setAttribute('y','610');text.setAttribute('fill','#60584c');text.setAttribute('font-family','Georgia,serif');text.setAttribute('font-size','18');for(const [i,line] of lines.entries()){const span=document.createElementNS('http://www.w3.org/2000/svg','tspan');span.setAttribute('x','30');span.setAttribute('dy',i?'24':'0');span.textContent=line;text.append(span)}clone.append(text);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='hall-of-scribbles.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Your page is ready to download. Keep it before leaving; this sheet does not autosave.'};

const actionDrawings={reset:['Start over','M12 18Q8 30 24 33Q39 32 36 18Q31 7 19 12L13 18 M12 10v9h9'],undo:['Undo last mark','M12 19h15q10 0 9 10q-1 8-12 6 M19 12l-8 7 8 7'], 'note-toggle':['A few words','M12 9l22 1-1 28-23-1Z M16 18l12-1m-12 7 11 1m-11 5h7'],download:['Keep this page','M13 10l20 1-1 27-20-1Z M23 15v15m-6-5 6 6 6-6']};
for(const [id,[label,path]] of Object.entries(actionDrawings)){const button=document.getElementById(id);button.setAttribute('aria-label',label);button.title=label;button.innerHTML=`<svg viewBox="0 0 46 46" aria-hidden="true"><path d="${path}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`}

document.querySelector('#back').href=import.meta.env.BASE_URL;
const notebookScript=document.createElement('script');notebookScript.src=import.meta.env.BASE_URL+'travel-notebook.js';notebookScript.onload=()=>window.mountNotebook({base:import.meta.env.BASE_URL,current:'drafts',places:destinations.map(p=>({...p,href:p.href?import.meta.env.BASE_URL+p.href:undefined}))});document.head.append(notebookScript);
